name: check

on: 
  push:
  workflow_dispatch:
  schedule:
   - cron: '0 3 * * 6'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: apt-get
      run: sudo apt-get install -q libyaml-perl liblwp-protocol-https-perl
    - name: check scripts
      run: perl ~/work/check-irssi-scripts/check-irssi-scripts/check.pl
